### ISSUE TITLE
3D Window pitch is capped

### ISSUE THREAD

**Issue by toomuchcookies** [mkeeter/antimony#116]
I just noticed that the camera pitch value in the 3d window is capped between -pi and 0. Proof:
https://www.youtube.com/watch?v=PJEDYQ5Ia4M&feature=youtu.be

**Comment by mkeeter** [comment]
This is intentional.

The rotation scheme is known as turntable rotation, where up on the screen always means up on the Z axis.  If we didn't cap Z rotation at the top and bottom, it would be possible to rotate around so that the model is upside-down.

Adding another rotation mode (e.g. arcball) may be a nice option.
